import React from 'react';
import {
  Activity,
  AlertCircle,
  ArrowLeft,
  BarChart3,
  Bike,
  Camera,
  CheckCircle2,
  ChevronRight,
  ClipboardList,
  Droplets,
  Dumbbell,
  Flame,
  Footprints,
  LayoutDashboard,
  Link2,
  List,
  Loader2,
  LogOut,
  MapPin,
  Minus,
  Moon,
  MoreHorizontal,
  Phone,
  Send,
  Settings,
  ShoppingCart,
  Sparkles,
  Store,
  ThumbsDown,
  ThumbsUp,
  Timer,
  Upload,
  UserCircle,
  UtensilsCrossed,
  Wand2,
  X,
} from 'lucide-react';
import {
  MealRecommendation,
  Merchant,
  OptionGroup,
  Order,
  OrderStatus,
  TaskCategory,
  TaskItem,
} from './types';
import { calculatePriceBreakdown, calculateUnitNutrition, productNutrition } from './utils/pricing';

export const ICONS = {
  Dashboard: <LayoutDashboard className="w-5 h-5" />,
  MealPlan: <UtensilsCrossed className="w-5 h-5" />,
  Profile: <UserCircle className="w-5 h-5" />,
  Admin: <Settings className="w-5 h-5" />,
  Activity: <Activity className="w-5 h-5" />,
  Water: <Droplets className="w-5 h-5" />,
  Calories: <Flame className="w-5 h-5" />,
  Location: <MapPin className="w-4 h-4" />,
  Camera: <Camera className="w-5 h-5" />,
  Magic: <Wand2 className="w-5 h-5" />,
  Loading: <Loader2 className="w-5 h-5 animate-spin" />,
  ArrowRight: <ChevronRight className="w-4 h-4" />,
  Upload: <Upload className="w-5 h-5" />,
  Send: <Send className="w-4 h-4" />,
  Dumbbell: <Dumbbell className="w-6 h-6" />,
  Footprints: <Footprints className="w-6 h-6" />,
  ThumbsUp: <ThumbsUp className="w-4 h-4" />,
  ThumbsDown: <ThumbsDown className="w-4 h-4" />,
  Minus: <Minus className="w-4 h-4" />,
  Check: <CheckCircle2 className="w-6 h-6" />,
  Timer: <Timer className="w-4 h-4" />,
  Delivery: <Bike className="w-3 h-3" />,
  Analytics: <BarChart3 className="w-5 h-5" />,
  Store: <Store className="w-5 h-5" />,
  Sparkles: <Sparkles className="w-4 h-4" />,
  Link: <Link2 className="w-4 h-4" />,
  Alert: <AlertCircle className="w-4 h-4" />,
  Logout: <LogOut className="w-5 h-5" />,
  More: <MoreHorizontal className="w-4 h-4" />,
  Moon: <Moon className="w-5 h-5" />,
  List: <List className="w-4 h-4" />,
  Close: <X className="w-4 h-4" />,
  ShoppingCart: <ShoppingCart className="w-5 h-5" />,
  Orders: <ClipboardList className="w-5 h-5" />,
  ArrowLeft: <ArrowLeft className="w-5 h-5" />,
  Phone: <Phone className="w-5 h-5" />,
};

export const MOCK_STATS = {
  calories: { current: 1250, target: 2200 },
  steps: { current: 5430, target: 8000 },
  water: { current: 1200, target: 2500 },
};

export const MOCK_TASKS: TaskItem[] = [
  { id: 't1', title: '晨間伸展 10 分鐘', category: TaskCategory.EXERCISE, isCompleted: true, description: '喚醒肌肉' },
  { id: 't2', title: '下肢肌力訓練（深蹲）', category: TaskCategory.EXERCISE, isCompleted: false, description: '目標 4 組 × 12 下' },
  { id: 't3', title: '記錄午餐熱量', category: TaskCategory.NUTRITION, isCompleted: false, description: '使用 AI 拍照功能' },
  { id: 't4', title: '喝水目標 2000cc', category: TaskCategory.NUTRITION, isCompleted: false, description: '目前進度：1200cc' },
  { id: 't5', title: '睡前冥想', category: TaskCategory.HABITS, isCompleted: false, description: '放鬆身心 10 分鐘' },
];

export const createDefaultOptionGroups = (prefix: string): OptionGroup[] => [
  {
    id: `${prefix}_rice`,
    name: '飯量',
    type: 'single',
    required: true,
    minSelect: 1,
    maxSelect: 1,
    options: [
      { id: `${prefix}_rice_normal`, name: '正常飯量', priceDelta: 0, caloriesDelta: 0, proteinDelta: 0, fatDelta: 0, carbsDelta: 0, fiberDelta: 0, sodiumDelta: 0, available: true },
      { id: `${prefix}_rice_half`, name: '飯量減半', priceDelta: 0, caloriesDelta: -100, proteinDelta: 0, fatDelta: 0, carbsDelta: -20, fiberDelta: 0, sodiumDelta: 0, available: true },
      { id: `${prefix}_rice_brown`, name: '換成糙米', priceDelta: 10, caloriesDelta: 10, proteinDelta: 1, fatDelta: 0, carbsDelta: 1, fiberDelta: 2, sodiumDelta: 0, available: true },
    ],
  },
  {
    id: `${prefix}_flavor`,
    name: '口味',
    type: 'single',
    required: true,
    minSelect: 1,
    maxSelect: 1,
    options: [
      { id: `${prefix}_sauce_side`, name: '醬料分開', priceDelta: 0, caloriesDelta: 0, proteinDelta: 0, fatDelta: 0, carbsDelta: 0, fiberDelta: 0, sodiumDelta: 0, available: true },
      { id: `${prefix}_less_salt`, name: '少鹽', priceDelta: 0, caloriesDelta: 0, proteinDelta: 0, fatDelta: 0, carbsDelta: 0, fiberDelta: 0, sodiumDelta: -100, available: true },
      { id: `${prefix}_less_oil`, name: '少油', priceDelta: 0, caloriesDelta: -35, proteinDelta: 0, fatDelta: -4, carbsDelta: 0, fiberDelta: 0, sodiumDelta: 0, available: true },
    ],
  },
  {
    id: `${prefix}_extras`,
    name: '加料',
    type: 'multiple',
    required: false,
    minSelect: 0,
    maxSelect: 2,
    options: [
      { id: `${prefix}_protein`, name: '加蛋白質', priceDelta: 30, caloriesDelta: 80, proteinDelta: 15, fatDelta: 1, carbsDelta: 0, fiberDelta: 0, sodiumDelta: 80, available: true },
      { id: `${prefix}_vegetables`, name: '增加蔬菜', priceDelta: 20, caloriesDelta: 25, proteinDelta: 1, fatDelta: 0, carbsDelta: 4, fiberDelta: 4, sodiumDelta: 20, available: true },
    ],
  },
];

export const MOCK_MERCHANTS: Merchant[] = [
  { id: 'merchant_self', name: '我的健康餐盒', phone: '02-2345-6789', address: '台北市信義區信義路五段7號', lat: 25.033, lng: 121.5654, hours: '11:00 - 20:30', deliveryFee: 30, serviceFee: 15, discount: 15, acceptingOrders: true },
  { id: 'merchant_muscle', name: 'Muscle Fuel 健康餐', phone: '02-2771-1234', address: '台北市大安區忠孝東路四段100號', lat: 25.041, lng: 121.55, hours: '10:30 - 20:00', deliveryFee: 30, serviceFee: 15, discount: 15, acceptingOrders: true },
  { id: 'merchant_daily', name: 'Daily Fresh 輕食', phone: '02-2345-6789', address: '台北市信義區松仁路100號', lat: 25.036, lng: 121.568, hours: '10:00 - 19:30', deliveryFee: 35, serviceFee: 15, discount: 0, acceptingOrders: true },
  { id: 'merchant_zhang', name: '老張健康滷', phone: '02-2888-9999', address: '台北市中山區南京東路二段88號', lat: 25.052, lng: 121.534, hours: '11:00 - 21:00', deliveryFee: 25, serviceFee: 12, discount: 0, acceptingOrders: true },
  { id: 'merchant_halo', name: 'Halo Poke', phone: '02-2700-1122', address: '台北市大安區復興南路一段200號', lat: 25.039, lng: 121.544, hours: '11:00 - 20:00', deliveryFee: 30, serviceFee: 15, discount: 10, acceptingOrders: true },
  { id: 'merchant_burger', name: 'Burger Fit', phone: '02-2766-5500', address: '台北市信義區基隆路一段100號', lat: 25.044, lng: 121.56, hours: '11:30 - 21:00', deliveryFee: 35, serviceFee: 15, discount: 0, acceptingOrders: true },
  { id: 'merchant_green', name: 'Green Day', phone: '02-2711-5566', address: '台北市松山區民生東路三段50號', lat: 25.058, lng: 121.545, hours: '09:00 - 19:00', deliveryFee: 30, serviceFee: 12, discount: 0, acceptingOrders: true },
  { id: 'merchant_yogurt', name: 'Yogurt House', phone: '02-2711-3344', address: '台北市松山區南京東路三段50號', lat: 25.052, lng: 121.546, hours: '08:00 - 20:00', deliveryFee: 30, serviceFee: 10, discount: 0, acceptingOrders: true },
];

const meal = (
  id: string,
  merchantId: string,
  merchant: string,
  name: string,
  price: number,
  calories: number,
  protein: number,
  fat: number,
  carbs: number,
  fiber: number,
  sodium: number,
  distance: number,
  imageUrl: string,
): MealRecommendation => ({
  id,
  merchantId,
  merchant,
  name,
  price,
  calories,
  macros: { protein, fat, carbs, sugar: 3, sodium, fiber },
  distance,
  imageUrl,
  available: true,
  optionGroups: createDefaultOptionGroups(id),
});

export const MOCK_MEALS: MealRecommendation[] = [
  meal('m1', 'merchant_muscle', 'Muscle Fuel 健康餐', '舒肥雞胸藜麥餐盒', 160, 450, 42, 8, 45, 6, 450, 0.3, 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=800&q=80'),
  meal('m2', 'merchant_daily', 'Daily Fresh 輕食', '香煎鮭魚五穀飯', 220, 580, 35, 18, 60, 7, 580, 1.2, 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80'),
  meal('m3', 'merchant_zhang', '老張健康滷', '低脂牛腱滷味拼盤', 130, 320, 30, 10, 15, 2, 850, 0.5, 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80'),
  meal('m4', 'merchant_halo', 'Halo Poke', '炙燒鮭魚波奇碗', 190, 480, 28, 12, 55, 5, 620, 0.8, 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80'),
  meal('m5', 'merchant_burger', 'Burger Fit', '增肌牛肉漢堡（無麵包）', 200, 520, 45, 25, 10, 3, 680, 2.5, 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80'),
  meal('m6', 'merchant_green', 'Green Day', '義式烤蔬菜溫沙拉', 150, 280, 12, 15, 30, 9, 320, 0.4, 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80'),
  meal('m7', 'merchant_self', '我的健康餐盒', '香草雞胸彩蔬餐盒', 170, 430, 40, 9, 42, 7, 420, 0.7, 'https://images.unsplash.com/photo-1546793665-c74683f339c1?auto=format&fit=crop&w=800&q=80'),
  meal('m8', 'merchant_yogurt', 'Yogurt House', '希臘優格高蛋白碗', 140, 350, 25, 5, 40, 5, 120, 0.6, 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=800&q=80'),
];

const sampleProduct = MOCK_MEALS[0];
const sampleOptions = [] as const;
const sampleBaseNutrition = productNutrition(sampleProduct);
const samplePrice = calculatePriceBreakdown(sampleProduct.price, [...sampleOptions]);
const sampleUnitNutrition = calculateUnitNutrition(sampleBaseNutrition, [...sampleOptions]);

export const MOCK_ORDERS: Order[] = [
  {
    orderId: 'HG20260728001',
    clientRequestId: 'seed-completed',
    merchantId: sampleProduct.merchantId,
    storeName: sampleProduct.merchant,
    storePhone: '02-2771-1234',
    items: [{
      id: 'seed-item-1',
      productId: sampleProduct.id,
      merchantId: sampleProduct.merchantId,
      merchantName: sampleProduct.merchant,
      name: sampleProduct.name,
      itemName: sampleProduct.name,
      imageUrl: sampleProduct.imageUrl,
      quantity: 1,
      basePrice: sampleProduct.price,
      baseNutrition: sampleBaseNutrition,
      selectedOptions: [],
      priceBreakdown: samplePrice,
      unitNutrition: sampleUnitNutrition,
      customOptions: [],
      price: samplePrice.unitPrice,
      subtotal: samplePrice.unitPrice,
    }],
    subtotal: 160,
    totalAmount: 190,
    deliveryFee: 30,
    serviceFee: 15,
    discount: 15,
    address: '台北市大安區安和路一段165號',
    estimatedArrival: '19:30',
    createdAt: '2026-07-28T18:30:00+08:00',
    status: OrderStatus.COMPLETED,
    statusHistory: [
      { status: OrderStatus.PENDING, timestamp: '2026-07-28T18:30:00+08:00' },
      { status: OrderStatus.PREPARING, timestamp: '2026-07-28T18:32:00+08:00' },
      { status: OrderStatus.WAITING_DELIVERY, timestamp: '2026-07-28T18:50:00+08:00' },
      { status: OrderStatus.DELIVERING, timestamp: '2026-07-28T19:00:00+08:00' },
      { status: OrderStatus.COMPLETED, timestamp: '2026-07-28T19:25:00+08:00' },
    ],
    paymentMethod: 'LINE Pay',
    note: '',
    completedAt: '2026-07-28T19:25:00+08:00',
  },
];
